version: "3.9"

services:
  postgres:
    image: postgres:14.3
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: maac
      POSTGRES_DB: vehiculo
    ports:
      - "5432:5432"
    networks:
      - db_net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: elestio/pgadmin:REL-9_8
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - db_net

networks:
  db_net:

volumes:
  postgres_data:
